version: "3.7"

networks:
    app-network:
        driver: bridge

services:
    nginx:
        container_name: nginx
        build:
            context: ./containers/nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "433:433"
            - "8100:8100"
        networks:
            - app-network
        volumes:
            - .:/var/www
    db:
        container_name: pgsql
        build:
            context: ./containers/db
            dockerfile: Dockerfile
        image: pgsql-docker
        restart: unless-stopped
        expose:
            - "5432"
        ports:
            - "5433:5432"
        volumes:
            - ./containers/db/script:/docker-entrypoint-initdb.d
            - ./containers/db/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=app_db
            - POSTGRES_PASSWORD=app_db
        networks:
            - app-network
